import { mutation } from "./_generated/server";

export const seed = mutation({
  args: {},
  handler: async (ctx) => {
    // Clear existing products
    const existingProducts = await ctx.db.query("products").collect();
    for (const product of existingProducts) {
      await ctx.db.delete(product._id);
    }

    const products = [
      // ========== BOARDS - SKATEBOARDS ==========
      {
        name: "Street Pro Deck 7.5\"",
        description: "Professional grade skateboard deck with 7-ply maple construction. Perfect for street skating and technical tricks.",
        price: 5999, // $59.99
        imageUrl: "https://images.unsplash.com/photo-1547447134-cd3f5c716030?w=800",
        category: "Boards",
        subcategory: "Skateboards",
        productType: "Decks",
        size: "7.5",
        inStock: true,
        featured: true,
        createdAt: Date.now(),
      },
      {
        name: "Street Pro Deck 8.0\"",
        description: "Professional grade skateboard deck with 7-ply maple construction. Ideal for all-around skating.",
        price: 5999,
        imageUrl: "https://images.unsplash.com/photo-1547447134-cd3f5c716030?w=800",
        category: "Boards",
        subcategory: "Skateboards",
        productType: "Decks",
        size: "8.0",
        inStock: true,
        featured: true,
        createdAt: Date.now(),
      },
      {
        name: "Street Pro Deck 8.5\"",
        description: "Professional grade skateboard deck with 7-ply maple construction. Great for ramps and bowls.",
        price: 5999,
        imageUrl: "https://images.unsplash.com/photo-1547447134-cd3f5c716030?w=800",
        category: "Boards",
        subcategory: "Skateboards",
        productType: "Decks",
        size: "8.5",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Aluminum Skateboard Trucks 4.0\"",
        description: "Lightweight aluminum trucks with smooth turning radius. Perfect for smaller decks.",
        price: 3999,
        imageUrl: "https://images.unsplash.com/photo-1564982752979-d682fb485798?w=800",
        category: "Boards",
        subcategory: "Skateboards",
        productType: "Trucks",
        size: "4.0",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Aluminum Skateboard Trucks 5.0\"",
        description: "Durable aluminum trucks designed for stability and control. Standard size for most decks.",
        price: 3999,
        imageUrl: "https://images.unsplash.com/photo-1564982752979-d682fb485798?w=800",
        category: "Boards",
        subcategory: "Skateboards",
        productType: "Trucks",
        size: "5.0",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Aluminum Skateboard Trucks 6.0\"",
        description: "Heavy-duty aluminum trucks for larger decks. Maximum stability and durability.",
        price: 3999,
        imageUrl: "https://images.unsplash.com/photo-1564982752979-d682fb485798?w=800",
        category: "Boards",
        subcategory: "Skateboards",
        productType: "Trucks",
        size: "6.0",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Street Wheels 50mm",
        description: "High-quality polyurethane wheels. 101A hardness for smooth street skating.",
        price: 2999,
        imageUrl: "https://images.unsplash.com/photo-1595452767848-1d0ffa7f4d8c?w=800",
        category: "Boards",
        subcategory: "Skateboards",
        productType: "Wheels",
        size: "50mm",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Street Wheels 52mm",
        description: "Versatile polyurethane wheels. 99A hardness for all-terrain skating.",
        price: 2999,
        imageUrl: "https://images.unsplash.com/photo-1595452767848-1d0ffa7f4d8c?w=800",
        category: "Boards",
        subcategory: "Skateboards",
        productType: "Wheels",
        size: "52mm",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Street Complete 7.5\"",
        description: "Ready-to-ride complete skateboard. Includes deck, trucks, wheels, bearings, and grip tape.",
        price: 12999,
        imageUrl: "https://images.unsplash.com/photo-1520520731457-9283dd14aa66?w=800",
        category: "Boards",
        subcategory: "Skateboards",
        productType: "Completes",
        size: "7.5",
        inStock: true,
        featured: true,
        createdAt: Date.now(),
      },
      {
        name: "Street Complete 8.0\"",
        description: "Ready-to-ride complete skateboard. Perfect for beginners and intermediates.",
        price: 12999,
        imageUrl: "https://images.unsplash.com/photo-1520520731457-9283dd14aa66?w=800",
        category: "Boards",
        subcategory: "Skateboards",
        productType: "Completes",
        size: "8.0",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Street Complete 8.5\"",
        description: "Professional complete skateboard. High-quality components throughout.",
        price: 12999,
        imageUrl: "https://images.unsplash.com/photo-1520520731457-9283dd14aa66?w=800",
        category: "Boards",
        subcategory: "Skateboards",
        productType: "Completes",
        size: "8.5",
        inStock: true,
        createdAt: Date.now(),
      },

      // ========== BOARDS - LONGBOARDS ==========
      {
        name: "Cruiser Longboard Deck 7.5\"",
        description: "Bamboo and maple hybrid longboard deck. Perfect for cruising and carving.",
        price: 8999,
        imageUrl: "https://images.unsplash.com/photo-1593642532400-2682810df593?w=800",
        category: "Boards",
        subcategory: "Longboards",
        productType: "Decks",
        size: "7.5",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Cruiser Longboard Deck 8.0\"",
        description: "Durable longboard deck with flex for smooth rides. Great for commuting.",
        price: 8999,
        imageUrl: "https://images.unsplash.com/photo-1593642532400-2682810df593?w=800",
        category: "Boards",
        subcategory: "Longboards",
        productType: "Decks",
        size: "8.0",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Cruiser Longboard Deck 8.5\"",
        description: "Premium longboard deck with concave design. Maximum stability at speed.",
        price: 8999,
        imageUrl: "https://images.unsplash.com/photo-1593642532400-2682810df593?w=800",
        category: "Boards",
        subcategory: "Longboards",
        productType: "Decks",
        size: "8.5",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Longboard Reverse Kingpin Trucks 4.0\"",
        description: "Smooth-turning reverse kingpin trucks. Ideal for carving and cruising.",
        price: 4999,
        imageUrl: "https://images.unsplash.com/photo-1564982752979-d682fb485798?w=800",
        category: "Boards",
        subcategory: "Longboards",
        productType: "Trucks",
        size: "4.0",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Longboard Reverse Kingpin Trucks 5.0\"",
        description: "Stable reverse kingpin trucks with adjustable bushings.",
        price: 4999,
        imageUrl: "https://images.unsplash.com/photo-1564982752979-d682fb485798?w=800",
        category: "Boards",
        subcategory: "Longboards",
        productType: "Trucks",
        size: "5.0",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Longboard Reverse Kingpin Trucks 6.0\"",
        description: "Heavy-duty longboard trucks for downhill and freeride.",
        price: 4999,
        imageUrl: "https://images.unsplash.com/photo-1564982752979-d682fb485798?w=800",
        category: "Boards",
        subcategory: "Longboards",
        productType: "Trucks",
        size: "6.0",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Longboard Cruiser Wheels 50mm",
        description: "Soft 78A wheels for smooth rides over rough surfaces.",
        price: 3499,
        imageUrl: "https://images.unsplash.com/photo-1595452767848-1d0ffa7f4d8c?w=800",
        category: "Boards",
        subcategory: "Longboards",
        productType: "Wheels",
        size: "50mm",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Longboard Cruiser Wheels 52mm",
        description: "Versatile 80A wheels. Great grip and speed maintenance.",
        price: 3499,
        imageUrl: "https://images.unsplash.com/photo-1595452767848-1d0ffa7f4d8c?w=800",
        category: "Boards",
        subcategory: "Longboards",
        productType: "Wheels",
        size: "52mm",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Longboard Complete 7.5\"",
        description: "Complete longboard setup ready to cruise. Premium components included.",
        price: 16999,
        imageUrl: "https://images.unsplash.com/photo-1593642634315-48f5414c3ad9?w=800",
        category: "Boards",
        subcategory: "Longboards",
        productType: "Completes",
        size: "7.5",
        inStock: true,
        featured: true,
        createdAt: Date.now(),
      },
      {
        name: "Longboard Complete 8.0\"",
        description: "All-in-one longboard package. Perfect for beginners.",
        price: 16999,
        imageUrl: "https://images.unsplash.com/photo-1593642634315-48f5414c3ad9?w=800",
        category: "Boards",
        subcategory: "Longboards",
        productType: "Completes",
        size: "8.0",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Longboard Complete 8.5\"",
        description: "Professional longboard complete. High-performance setup.",
        price: 16999,
        imageUrl: "https://images.unsplash.com/photo-1593642634315-48f5414c3ad9?w=800",
        category: "Boards",
        subcategory: "Longboards",
        productType: "Completes",
        size: "8.5",
        inStock: true,
        createdAt: Date.now(),
      },

      // ========== BOARDS - PENNYBOARDS ==========
      {
        name: "Mini Cruiser Deck 4.0\"",
        description: "Compact plastic deck perfect for portability. Retro style cruiser.",
        price: 3999,
        imageUrl: "https://images.unsplash.com/photo-1547447134-cd3f5c716030?w=800",
        category: "Boards",
        subcategory: "Pennyboards",
        productType: "Decks",
        size: "4.0",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Mini Cruiser Deck 5.0\"",
        description: "Classic penny-style deck with waffle grip pattern.",
        price: 3999,
        imageUrl: "https://images.unsplash.com/photo-1547447134-cd3f5c716030?w=800",
        category: "Boards",
        subcategory: "Pennyboards",
        productType: "Decks",
        size: "5.0",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Mini Cruiser Deck 6.0\"",
        description: "Larger penny deck for more foot space and stability.",
        price: 3999,
        imageUrl: "https://images.unsplash.com/photo-1547447134-cd3f5c716030?w=800",
        category: "Boards",
        subcategory: "Pennyboards",
        productType: "Decks",
        size: "6.0",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Penny Trucks 4.0\"",
        description: "Lightweight aluminum trucks designed for penny boards.",
        price: 2499,
        imageUrl: "https://images.unsplash.com/photo-1564982752979-d682fb485798?w=800",
        category: "Boards",
        subcategory: "Pennyboards",
        productType: "Trucks",
        size: "4.0",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Penny Trucks 5.0\"",
        description: "Durable trucks for penny cruisers. Smooth turning action.",
        price: 2499,
        imageUrl: "https://images.unsplash.com/photo-1564982752979-d682fb485798?w=800",
        category: "Boards",
        subcategory: "Pennyboards",
        productType: "Trucks",
        size: "5.0",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Penny Trucks 6.0\"",
        description: "Heavy-duty penny trucks for larger cruiser boards.",
        price: 2499,
        imageUrl: "https://images.unsplash.com/photo-1564982752979-d682fb485798?w=800",
        category: "Boards",
        subcategory: "Pennyboards",
        productType: "Trucks",
        size: "6.0",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Penny Wheels 50mm",
        description: "Soft 78A wheels for smooth cruising on any surface.",
        price: 1999,
        imageUrl: "https://images.unsplash.com/photo-1595452767848-1d0ffa7f4d8c?w=800",
        category: "Boards",
        subcategory: "Pennyboards",
        productType: "Wheels",
        size: "50mm",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Penny Wheels 52mm",
        description: "High-rebound wheels for fast and smooth rides.",
        price: 1999,
        imageUrl: "https://images.unsplash.com/photo-1595452767848-1d0ffa7f4d8c?w=800",
        category: "Boards",
        subcategory: "Pennyboards",
        productType: "Wheels",
        size: "52mm",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Penny Complete 4.0\"",
        description: "Ready-to-ride mini cruiser. Ultra-portable and fun.",
        price: 7999,
        imageUrl: "https://images.unsplash.com/photo-1547447134-cd3f5c716030?w=800",
        category: "Boards",
        subcategory: "Pennyboards",
        productType: "Completes",
        size: "4.0",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Penny Complete 5.0\"",
        description: "Classic penny board complete. Perfect for commuting.",
        price: 7999,
        imageUrl: "https://images.unsplash.com/photo-1547447134-cd3f5c716030?w=800",
        category: "Boards",
        subcategory: "Pennyboards",
        productType: "Completes",
        size: "5.0",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Penny Complete 6.0\"",
        description: "Larger penny complete with more stability.",
        price: 7999,
        imageUrl: "https://images.unsplash.com/photo-1547447134-cd3f5c716030?w=800",
        category: "Boards",
        subcategory: "Pennyboards",
        productType: "Completes",
        size: "6.0",
        inStock: true,
        createdAt: Date.now(),
      },

      // ========== HARDWARE ==========
      {
        name: "Allen Head Mounting Bolts - Black",
        description: "Set of 8 high-quality steel bolts with allen head design. 7/8 inch length.",
        price: 599,
        imageUrl: "https://images.unsplash.com/photo-1530124566582-a618bc2615dc?w=800",
        category: "Hardware",
        subcategory: "Bolts",
        productType: "Bolts",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Phillips Head Mounting Bolts - Silver",
        description: "Set of 8 durable steel bolts. Standard 1 inch length.",
        price: 499,
        imageUrl: "https://images.unsplash.com/photo-1530124566582-a618bc2615dc?w=800",
        category: "Hardware",
        subcategory: "Bolts",
        productType: "Bolts",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Colored Hardware Set - Red",
        description: "Set of 8 colored bolts to customize your board. Allen head design.",
        price: 799,
        imageUrl: "https://images.unsplash.com/photo-1530124566582-a618bc2615dc?w=800",
        category: "Hardware",
        subcategory: "Bolts",
        productType: "Bolts",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Black Diamond Griptape",
        description: "Premium griptape with superior adhesion. 9\" x 33\" sheet.",
        price: 899,
        imageUrl: "https://images.unsplash.com/photo-1564982752979-d682fb485798?w=800",
        category: "Hardware",
        subcategory: "Griptape",
        productType: "Griptape",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Clear Perforated Griptape",
        description: "See-through griptape to show off your deck graphic. Bubble-free application.",
        price: 1299,
        imageUrl: "https://images.unsplash.com/photo-1564982752979-d682fb485798?w=800",
        category: "Hardware",
        subcategory: "Griptape",
        productType: "Griptape",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Colored Griptape - Blue",
        description: "Vibrant colored griptape. Same grip as black, more style.",
        price: 999,
        imageUrl: "https://images.unsplash.com/photo-1564982752979-d682fb485798?w=800",
        category: "Hardware",
        subcategory: "Griptape",
        productType: "Griptape",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Shock Absorbing Risers - 1/8\"",
        description: "Hard plastic risers to prevent wheel bite and reduce vibration.",
        price: 399,
        imageUrl: "https://images.unsplash.com/photo-1530124566582-a618bc2615dc?w=800",
        category: "Hardware",
        subcategory: "Risers",
        productType: "Risers",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Angled Wedge Risers - 1/4\"",
        description: "Angled risers for improved turning radius. Set of 2.",
        price: 599,
        imageUrl: "https://images.unsplash.com/photo-1530124566582-a618bc2615dc?w=800",
        category: "Hardware",
        subcategory: "Risers",
        productType: "Risers",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Soft Rubber Risers - 1/2\"",
        description: "Maximum shock absorption for rough terrain. Set of 2.",
        price: 799,
        imageUrl: "https://images.unsplash.com/photo-1530124566582-a618bc2615dc?w=800",
        category: "Hardware",
        subcategory: "Risers",
        productType: "Risers",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "ABEC 7 Bearings",
        description: "Set of 8 precision ABEC 7 bearings. Fast and smooth.",
        price: 1999,
        imageUrl: "https://images.unsplash.com/photo-1595452767848-1d0ffa7f4d8c?w=800",
        category: "Hardware",
        subcategory: "Bearings",
        productType: "Bearings",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "ABEC 9 Bearings",
        description: "High-performance ABEC 9 bearings. Set of 8 with spacers.",
        price: 2999,
        imageUrl: "https://images.unsplash.com/photo-1595452767848-1d0ffa7f4d8c?w=800",
        category: "Hardware",
        subcategory: "Bearings",
        productType: "Bearings",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Ceramic Bearings - Pro Series",
        description: "Premium ceramic bearings for maximum speed. Set of 8.",
        price: 4999,
        imageUrl: "https://images.unsplash.com/photo-1595452767848-1d0ffa7f4d8c?w=800",
        category: "Hardware",
        subcategory: "Bearings",
        productType: "Bearings",
        inStock: true,
        createdAt: Date.now(),
      },

      // ========== APPAREL - T-SHIRTS ==========
      {
        name: "Ollie North Logo Tee - S",
        description: "Classic fit t-shirt with Ollie North logo. 100% cotton.",
        price: 2499,
        imageUrl: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800",
        category: "Apparel",
        subcategory: "T-Shirts",
        productType: "T-Shirts",
        size: "S",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Ollie North Logo Tee - M",
        description: "Classic fit t-shirt with Ollie North logo. 100% cotton.",
        price: 2499,
        imageUrl: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800",
        category: "Apparel",
        subcategory: "T-Shirts",
        productType: "T-Shirts",
        size: "M",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Ollie North Logo Tee - L",
        description: "Classic fit t-shirt with Ollie North logo. 100% cotton.",
        price: 2499,
        imageUrl: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800",
        category: "Apparel",
        subcategory: "T-Shirts",
        productType: "T-Shirts",
        size: "L",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Ollie North Logo Tee - XXL",
        description: "Classic fit t-shirt with Ollie North logo. 100% cotton.",
        price: 2499,
        imageUrl: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800",
        category: "Apparel",
        subcategory: "T-Shirts",
        productType: "T-Shirts",
        size: "XXL",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Skate or Die Graphic Tee - S",
        description: "Bold graphic t-shirt with vintage skate design. Soft ringspun cotton.",
        price: 2799,
        imageUrl: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800",
        category: "Apparel",
        subcategory: "T-Shirts",
        productType: "T-Shirts",
        size: "S",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Skate or Die Graphic Tee - M",
        description: "Bold graphic t-shirt with vintage skate design. Soft ringspun cotton.",
        price: 2799,
        imageUrl: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800",
        category: "Apparel",
        subcategory: "T-Shirts",
        productType: "T-Shirts",
        size: "M",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Skate or Die Graphic Tee - L",
        description: "Bold graphic t-shirt with vintage skate design. Soft ringspun cotton.",
        price: 2799,
        imageUrl: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800",
        category: "Apparel",
        subcategory: "T-Shirts",
        productType: "T-Shirts",
        size: "L",
        inStock: true,
        featured: true,
        createdAt: Date.now(),
      },
      {
        name: "Skate or Die Graphic Tee - XXL",
        description: "Bold graphic t-shirt with vintage skate design. Soft ringspun cotton.",
        price: 2799,
        imageUrl: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800",
        category: "Apparel",
        subcategory: "T-Shirts",
        productType: "T-Shirts",
        size: "XXL",
        inStock: true,
        createdAt: Date.now(),
      },

      // ========== APPAREL - HOODIES ==========
      {
        name: "Pullover Hoodie - S",
        description: "Comfortable pullover hoodie with kangaroo pocket. 80/20 cotton/poly blend.",
        price: 4999,
        imageUrl: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800",
        category: "Apparel",
        subcategory: "Hoodies",
        productType: "Hoodies",
        size: "S",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Pullover Hoodie - M",
        description: "Comfortable pullover hoodie with kangaroo pocket. 80/20 cotton/poly blend.",
        price: 4999,
        imageUrl: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800",
        category: "Apparel",
        subcategory: "Hoodies",
        productType: "Hoodies",
        size: "M",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Pullover Hoodie - L",
        description: "Comfortable pullover hoodie with kangaroo pocket. 80/20 cotton/poly blend.",
        price: 4999,
        imageUrl: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800",
        category: "Apparel",
        subcategory: "Hoodies",
        productType: "Hoodies",
        size: "L",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Pullover Hoodie - XXL",
        description: "Comfortable pullover hoodie with kangaroo pocket. 80/20 cotton/poly blend.",
        price: 4999,
        imageUrl: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800",
        category: "Apparel",
        subcategory: "Hoodies",
        productType: "Hoodies",
        size: "XXL",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Zip-Up Hoodie - S",
        description: "Full-zip hoodie with pockets. Fleece-lined for warmth.",
        price: 5499,
        imageUrl: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800",
        category: "Apparel",
        subcategory: "Hoodies",
        productType: "Hoodies",
        size: "S",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Zip-Up Hoodie - M",
        description: "Full-zip hoodie with pockets. Fleece-lined for warmth.",
        price: 5499,
        imageUrl: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800",
        category: "Apparel",
        subcategory: "Hoodies",
        productType: "Hoodies",
        size: "M",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Zip-Up Hoodie - L",
        description: "Full-zip hoodie with pockets. Fleece-lined for warmth.",
        price: 5499,
        imageUrl: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800",
        category: "Apparel",
        subcategory: "Hoodies",
        productType: "Hoodies",
        size: "L",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Zip-Up Hoodie - XXL",
        description: "Full-zip hoodie with pockets. Fleece-lined for warmth.",
        price: 5499,
        imageUrl: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800",
        category: "Apparel",
        subcategory: "Hoodies",
        productType: "Hoodies",
        size: "XXL",
        inStock: true,
        createdAt: Date.now(),
      },

      // ========== APPAREL - PANTS ==========
      {
        name: "Skate Jeans - 29",
        description: "Relaxed fit denim with reinforced knees. Built for skating.",
        price: 5999,
        imageUrl: "https://images.unsplash.com/photo-1542272454315-7f6d6e106672?w=800",
        category: "Apparel",
        subcategory: "Pants",
        productType: "Pants",
        size: "29",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Skate Jeans - 32",
        description: "Relaxed fit denim with reinforced knees. Built for skating.",
        price: 5999,
        imageUrl: "https://images.unsplash.com/photo-1542272454315-7f6d6e106672?w=800",
        category: "Apparel",
        subcategory: "Pants",
        productType: "Pants",
        size: "32",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Skate Jeans - 36",
        description: "Relaxed fit denim with reinforced knees. Built for skating.",
        price: 5999,
        imageUrl: "https://images.unsplash.com/photo-1542272454315-7f6d6e106672?w=800",
        category: "Apparel",
        subcategory: "Pants",
        productType: "Pants",
        size: "36",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Cargo Pants - 29",
        description: "Durable cargo pants with multiple pockets. Comfortable fit.",
        price: 4999,
        imageUrl: "https://images.unsplash.com/photo-1542272454315-7f6d6e106672?w=800",
        category: "Apparel",
        subcategory: "Pants",
        productType: "Pants",
        size: "29",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Cargo Pants - 32",
        description: "Durable cargo pants with multiple pockets. Comfortable fit.",
        price: 4999,
        imageUrl: "https://images.unsplash.com/photo-1542272454315-7f6d6e106672?w=800",
        category: "Apparel",
        subcategory: "Pants",
        productType: "Pants",
        size: "32",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Cargo Pants - 36",
        description: "Durable cargo pants with multiple pockets. Comfortable fit.",
        price: 4999,
        imageUrl: "https://images.unsplash.com/photo-1542272454315-7f6d6e106672?w=800",
        category: "Apparel",
        subcategory: "Pants",
        productType: "Pants",
        size: "36",
        inStock: true,
        createdAt: Date.now(),
      },

      // ========== APPAREL - SHOES ==========
      {
        name: "Skate Shoes - Size 8",
        description: "Durable canvas and suede skate shoes. Vulcanized sole for board feel.",
        price: 6999,
        imageUrl: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800",
        category: "Apparel",
        subcategory: "Shoes",
        productType: "Shoes",
        size: "8",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Skate Shoes - Size 9.5",
        description: "Durable canvas and suede skate shoes. Vulcanized sole for board feel.",
        price: 6999,
        imageUrl: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800",
        category: "Apparel",
        subcategory: "Shoes",
        productType: "Shoes",
        size: "9.5",
        inStock: true,
        featured: true,
        createdAt: Date.now(),
      },
      {
        name: "Skate Shoes - Size 10",
        description: "Durable canvas and suede skate shoes. Vulcanized sole for board feel.",
        price: 6999,
        imageUrl: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800",
        category: "Apparel",
        subcategory: "Shoes",
        productType: "Shoes",
        size: "10",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "Skate Shoes - Size 11",
        description: "Durable canvas and suede skate shoes. Vulcanized sole for board feel.",
        price: 6999,
        imageUrl: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800",
        category: "Apparel",
        subcategory: "Shoes",
        productType: "Shoes",
        size: "11",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "High-Top Skate Shoes - Size 8",
        description: "Classic high-top design with ankle support. Padded collar.",
        price: 7999,
        imageUrl: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800",
        category: "Apparel",
        subcategory: "Shoes",
        productType: "Shoes",
        size: "8",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "High-Top Skate Shoes - Size 9.5",
        description: "Classic high-top design with ankle support. Padded collar.",
        price: 7999,
        imageUrl: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800",
        category: "Apparel",
        subcategory: "Shoes",
        productType: "Shoes",
        size: "9.5",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "High-Top Skate Shoes - Size 10",
        description: "Classic high-top design with ankle support. Padded collar.",
        price: 7999,
        imageUrl: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800",
        category: "Apparel",
        subcategory: "Shoes",
        productType: "Shoes",
        size: "10",
        inStock: true,
        createdAt: Date.now(),
      },
      {
        name: "High-Top Skate Shoes - Size 11",
        description: "Classic high-top design with ankle support. Padded collar.",
        price: 7999,
        imageUrl: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800",
        category: "Apparel",
        subcategory: "Shoes",
        productType: "Shoes",
        size: "11",
        inStock: true,
        createdAt: Date.now(),
      },
    ];

    for (const product of products) {
      await ctx.db.insert("products", {
        ...product,
        stockQuantity: Math.floor(Math.random() * 50) + 10, // Random stock between 10-60
      });
    }

    return { success: true, count: products.length };
  },
});